### ISSUE TITLE
How to view vignette?

### ISSUE THREAD

**Issue by theo-allnutt-bioinformatics** [nyiuab/NBZIMM#2]
How do you view the vignette?
> library(NBZIMM)
> vignette(NBZIMM)
Error in vignette(NBZIMM) : object 'NBZIMM' not found

**Comment by boyiguo1** [comment]
Please use the following command
```{r}
vignette(package="NBZIMM")
```
If you use R studio, you can simply go to "packages" panel, find NBZIMM package and click on "User guides, package vignettes and other documentation" hyperlink, via the graphic user interface.
